# This workflow will do a clean install of node dependencies, build the source code and run tests across different OSs
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-node@v5
      with:
        node-version: 22
    - run: npm ci
    - run: npm run build --if-present
    - name: Run tests (Linux)
      run: xvfb-run -a npm run test
      if: runner.os == 'Linux'
    - name: Run tests (macOS)
      run: npm run test
      if: runner.os == 'macOS'
    - name: Run tests (Windows)
      run: npm run test
      if: runner.os == 'Windows'
